import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';

// Load .env for OBSIDIAN_DEV_VAULT_PATH (dev-only; not bundled into plugin)
let devVaultPath = null;
try {
  const { config } = await import('dotenv');
  const result = config();
  if (!result.error) {
    devVaultPath = process.env.OBSIDIAN_DEV_VAULT_PATH ?? null;
  }
} catch {
  // dotenv not available or .env missing — dev vault copy disabled
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the GitHub repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/**
 * CSS files in src/styles/ — order matters, edit here when adding a new feature file.
 * Each file owns one feature; agents should only edit the relevant file.
 */
const CSS_FILES = [
  '_utilities',
  'runner-view',
  'canvas-selector',
  'editor-panel',
  'snippet-manager',
  'snippet-fill-modal',
  'loop-support',
  'snippet-tree-picker',
  'inline-runner',
  'donate-section',
];

/**
 * Concatenates src/styles/*.css in CSS_FILES order → styles.css after each build.
 * Obsidian loads styles.css from the plugin root.
 */
const cssPlugin = {
  name: 'css-concat',
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return;
      try {
        const parts = CSS_FILES.map((name) => {
          const filePath = `src/styles/${name}.css`;
          return fs.readFileSync(filePath, 'utf8');
        });
        const combined = parts.join('\n');
        fs.writeFileSync('styles.css', combined);
      } catch (err) {
        console.error(`[radiprotocol] CSS concat failed: ${err.message}`);
      }
    });
  },
};

/**
 * Copies main.js and manifest.json to the dev vault plugin directory after each build.
 * Only runs when OBSIDIAN_DEV_VAULT_PATH is set in .env and build succeeds.
 */
const devVaultCopyPlugin = {
  name: 'dev-vault-copy',
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return;
      if (!devVaultPath) return;

      const pluginDir = path.join(
        devVaultPath,
        '.obsidian',
        'plugins',
        'radiprotocol'
      );

      try {
        fs.mkdirSync(pluginDir, { recursive: true });
        fs.copyFileSync('main.js', path.join(pluginDir, 'main.js'));
        fs.copyFileSync('manifest.json', path.join(pluginDir, 'manifest.json'));
        if (fs.existsSync('styles.css')) {
          fs.copyFileSync('styles.css', path.join(pluginDir, 'styles.css'));
        }
        console.debug(`[radiprotocol] Copied to dev vault: ${pluginDir}`);
      } catch (err) {
        console.error(`[radiprotocol] Dev vault copy failed: ${err.message}`);
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  plugins: [cssPlugin, devVaultCopyPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
